### ISSUE TITLE
 Huey::Request.register fails with "username, not available"

### ISSUE THREAD

**Issue by FreeApophis** [joshsymonds/huey#26]
Error:
 Huey::Request.register
Huey::Errors::HueResponseError: [{"error"=>{"type"=>6, "address"=>"/username", "description"=>"parameter, username, not available"}}]
        from /var/lib/gems/1.9.1/gems/huey-2.1.0/lib/huey/request.rb:47:in `error?'
        from /var/lib/gems/1.9.1/gems/huey-2.1.0/lib/huey/request.rb:27:in `register'
        from (irb):4
        from /usr/bin/irb:12:in `<main>'

Probable cause, Api change, a username parameter is no longer allowed.

https://developers.meethue.com/documentation/important-whitelist-changes

Pullrequest 24 should fix this.

**Comment by FreeApophis** [comment]
OK another dead project...
